### ISSUE TITLE
Optimize gif size

### ISSUE THREAD

**Issue by mzfr** [dn1z/pgn2gif#4]
Currently the size of the gifs generated is very large. Ex: pgn having only 10 moves results in gif of size around 2 MB.

Optimizations for the gifs generated must be added.

**Comment by dn1z** [comment]
Rather than optimization, I should reduce image size. 640x640 is seems much for gif whereas 480x480 is ideal. It would reduce size by about 36/64 which is nearly half. I will update it to 480x480 in a week.

Also thanks for all care you showed and helped me. I'm still newbie in programming (about 4-5 months) and your aids already helped me a lot. Thanks for again.

By the way sorry for being late. I was a little bit busy in past weeks.
